apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-ns-sync
  labels:
    app: cf-ns-sync
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cf-ns-sync
  template:
    metadata:
      labels:
        app: cf-ns-sync
    spec:
      serviceAccountName: cf-ns-sync-sa
      containers:
      - name: cf-ns-sync
        image: ghcr.io/das6ng/k8s-cf-ns-sync:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_LEVEL
          # should be DEBUG/INFO/WARN/ERROR
          value: INFO
        - name: MONITOR_NS
          # namespaces to be monitored, comma separated
          value: default
        envFrom:
        - secretRef:
            # make SURE you've created this secret, it contains:
            # CLOUDFLARE_API_TOKEN : your cloudflare api token
            # CLOUDFLARE_ZONE_NAME : your domain name
            name: cf-ns-sync-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cf-ns-sync
  name: cf-ns-sync-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cf-ns-sync-ingress-watcher
  labels:
    app: cf-ns-sync
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cf-ns-sync-watch-ingress
  labels:
    app: cf-ns-sync
  namespace: default
roleRef:
  kind: ClusterRole
  name: cf-ns-sync-ingress-watcher
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cf-ns-sync-sa
  apiGroup: ""
  namespace: default
