apiVersion: v1
kind: Secret
metadata:
  name: cf-ns-sync-secret
  namespace: default
type: Opaque
# make SURE you've set these data to your own
stringData:
  # https://dash.cloudflare.com/profile/api-tokens
  # the token MUST have the following Permissions on your target zone:
  #     Zone    DNS    Read
  #     Zone    DNS    Edit
  CLOUDFLARE_API_TOKEN: <your own cloudflare api_token>
  CLOUDFLARE_ZONE_NAME: <your own domain name>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-ns-sync
  labels:
    app: cf-ns-sync
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cf-ns-sync
  template:
    metadata:
      labels:
        app: cf-ns-sync
    spec:
      serviceAccountName: cf-ns-sync-sa
      containers:
        - name: cf-ns-sync
          image: ghcr.io/das6ng/k8s-cf-ns-sync:latest
          imagePullPolicy: IfNotPresent
          args:
            - --mode
            - exclude
            - --cloudflare-zone
            - "$(CLOUDFLARE_ZONE_NAME)"
            - --cloudflare-api-token
            - "$(CLOUDFLARE_API_TOKEN)"
          env:
            - name: LOG_LEVEL
              # should be DEBUG/INFO/WARN/ERROR
              value: INFO
          envFrom:
            - secretRef:
                name: cf-ns-sync-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cf-ns-sync
  name: cf-ns-sync-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cf-ns-sync-ingress-watcher
  labels:
    app: cf-ns-sync
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cf-ns-sync-watch-ingress
  labels:
    app: cf-ns-sync
  namespace: default
roleRef:
  kind: ClusterRole
  name: cf-ns-sync-ingress-watcher
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: cf-ns-sync-sa
    apiGroup: ""
    namespace: default
